// scripts/seed-sfx.ts
import { db } from '../src/lib/firebase-admin';
import type { SoundEffect } from '../src/lib/types';

// This data is now self-contained within the script that uses it.
// IMPORTANT: Replace [YOUR_TOKEN_HERE] with the actual token from the Firebase Console's "Download URL".
const mockSoundEffectsLibrary: SoundEffect[] = [
  { id: 'sfx_001', name: 'Comical Boing', tags: ['boing', 'jump', 'funny'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcomical-boing.mp3?alt=media&token=b870cf76-e00a-4dad-b448-dfb19bd93b1d' },
  { id: 'sfx_002', name: 'Dramatic Swell', tags: ['swell', 'tension', 'reveal'], tone: ['Dramatic', 'Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fdramatic-swell.mp3?alt=media&token=b0479953-8dd9-4f20-986a-fc1186107eab' },
  { id: 'sfx_003', name: 'Suspenseful Drone', tags: ['drone', 'creepy', 'tense'], tone: ['Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fsuspenseful-drone.mp3?alt=media&token=31134557-c428-4153-b786-cfdf6ff2ecfb' },
  { id: 'sfx_004', name: 'Uplifting Chime', tags: ['chime', 'positive', 'success'], tone: ['Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fuplifting-chime.mp3?alt=media&token=6428c1a6-03f9-4da6-a3e6-af22601d0d97' },
  { id: 'sfx_005', name: 'Sad Trombone', tags: ['fail', 'wah-wah', 'funny'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fsad-trombone.mp3?alt=media&token=7f44ee43-7f9b-4abc-88ed-020a4a6b6e12' },
  { id: 'sfx_006', name: 'Heartbeat', tags: ['heart', 'pulse', 'tense'], tone: ['Suspenseful', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fheartbeat.mp3?alt=media&token=2d8cc827-cc0e-4006-b8ae-0707c4635013' },
  { id: 'sfx_007', name: 'Record Scratch', tags: ['stop', 'interrupt', 'funny'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Frecord-scratch.mp3?alt=media&token=18f2d377-fc22-4d37-b18e-2397d60bcb2e' },
  { id: 'sfx_008', name: 'Inspiring Piano Chord', tags: ['piano', 'hopeful', 'positive'], tone: ['Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Finspiring-chord.mp3?alt=media&token=bac431ee-912c-4366-8cc9-3495e33a6673' },
  { id: 'sfx_009', name: 'Gong', tags: ['gong', 'chime', 'meditation', 'reveal', 'announcement', 'dramatic'], tone: ['Dramatic', 'Comedic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fold-zildjian-gong.mp3?alt=media&token=908594e0-a511-42eb-8651-d81d7c06d1de' },
  { id: 'sfx_010', name: 'Airplane Landing', tags: ['airplane', 'landing', 'plane', 'airport', 'travel', 'arrival'], tone: ['Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fairplane-landing.mp3?alt=media&token=fa230a1d-8ddb-49be-b78c-5ea1c5c44341' },
  { id: 'sfx_011', name: 'Crowd Argument', tags: ['crowd', 'argument', 'arguing', 'yelling', 'shouting', 'conflict', 'mob'], tone: ['Dramatic', 'Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcrowd-argument.mp3?alt=media&token=cfdad448-a9af-47b5-9300-31b5ae47052c' },
  { id: 'sfx_012', name: 'Crazy Laugh', tags: ['laugh', 'laughter', 'crazy', 'maniacal', 'evil', 'joker'], tone: ['Comedic', 'Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Flaugh-like-crazy.mp3?alt=media&token=88a371b8-b970-4c96-ba18-f603ee5b31a0' },
  { id: 'sfx_013', name: 'Cat Meow', tags: ['cat', 'meow', 'kitten', 'animal', 'cute'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fmeow.mp3?alt=media&token=9c48d39a-4540-4de9-94b8-8fa2a41ea1e2' },
  { id: 'sfx_014', name: 'Printer', tags: ['printer', 'printing', 'office', 'work', 'paper', 'machine'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fprinter-sound.mp3?alt=media&token=7a7b00cc-d33c-4f86-9d3b-58d4f8a19983' },
  { id: 'sfx_015', name: 'Party Horn', tags: ['party', 'horn', 'celebration', 'birthday', 'surprise', 'new years'], tone: ['Comedic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fparty-horn.mp3?alt=media&token=4f997fc3-0179-472b-8334-21d1534ddd84' },
  { id: 'sfx_016', name: 'Horror Chase Music', tags: ['horror', 'chase', 'scary', 'running', 'monster', 'tense'], tone: ['Suspenseful', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fhorror-chase-music.mp3?alt=media&token=97d9a279-9ee0-4236-882a-bafc8353c620' },
  { id: 'sfx_017', name: 'Crying Infant', tags: ['crying', 'baby', 'infant', 'sad', 'upset', 'wailing'], tone: ['Dramatic', 'Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcrying_infant.mp3?alt=media&token=899556ce-8d65-41bb-b853-be2b4d8fc4f0' },
  { id: 'sfx_018', name: 'Angelic Epiphany Choir', tags: ['angelic', 'choir', 'heavenly', 'epiphany', 'reveal', 'hallelujah', 'holy'], tone: ['Inspirational', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fangelic-epiphany-choir.mp3?alt=media&token=a1805e3e-cd47-456d-a300-f0518e09a08a' },
  { id: 'sfx_019', name: 'Jet Plane', tags: ['jet', 'plane', 'flyby', 'fast', 'whoosh', 'sound barrier'], tone: ['Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fjet-plane-flyby.mp3?alt=media&token=17a85ec3-54d9-4a3a-bd97-6e844bbfafb3' },
  { id: 'sfx_020', name: 'Car Alarm', tags: ['car', 'alarm', 'siren', 'theft', 'annoying', 'emergency'], tone: ['Suspenseful', 'Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcar-alarm.mp3?alt=media&token=618768cc-1ce5-445a-a074-044362ac12e6' },
  { id: 'sfx_021', name: 'Angry Mob', tags: ['mob', 'angry', 'crowd', 'riot', 'protest', 'yelling'], tone: ['Dramatic', 'Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fangry-mob.mp3?alt=media&token=ed456719-0716-47e7-9422-f9887bc50332' },
  { id: 'sfx_022', name: 'Going Up Bouncy', tags: ['up', 'bouncy', 'ascend', 'level up', 'positive', 'jump'], tone: ['Comedic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fgoing-up-bouncy.mp3?alt=media&token=37ad285c-ad93-4f87-88d1-5f227150852a' },
  { id: 'sfx_023', name: 'Computer Processing', tags: ['computer', 'processing', 'calculating', 'thinking', 'tech', 'data'], tone: ['Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcomputer-processing.mp3?alt=media&token=5ae6350e-756a-44f1-91a8-e617806a9c86' },
  { id: 'sfx_024', name: 'Socket Wrench', tags: ['wrench', 'ratchet', 'tools', 'mechanic', 'fixing', 'repair'], tone: ['Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fsocket-wrench.mp3?alt=media&token=539a678b-713d-41d8-81bc-90fc9411b041' },
  { id: 'sfx_025', name: 'Ufo Transition', tags: ['ufo', 'transition', 'alien', 'sci-fi', 'space', 'weird', 'whoosh'], tone: ['Suspenseful', 'Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fufo-transition.mp3?alt=media&token=fb3b9056-b9b1-44d8-86bc-64113e8c969a' },
  { id: 'sfx_026', name: 'Small Dog Barking', tags: ['dog', 'barking', 'small dog', 'puppy', 'yapping', 'animal'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fsmall-dog-barking.mp3?alt=media&token=992b8958-ef66-4004-96a1-af5ee2a0b7e1' },
  { id: 'sfx_027', name: 'Woman Sobbing', tags: ['sobbing', 'crying', 'sad', 'woman', 'emotional', 'weeping'], tone: ['Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fa-woman-sobbing.mp3?alt=media&token=527bd64c-6587-4129-82e1-ba43b1122362' },
  { id: 'sfx_028', name: 'Robot Noises', tags: ['robot', 'noises', 'robotic', 'bleep', 'bloop', 'sci-fi', 'android'], tone: ['Comedic', 'Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Frobot-noises.mp3?alt=media&token=86ce0f43-9ae5-4898-b689-98e5c4d9bbfb' },
  { id: 'sfx_029', name: 'Light Switch', tags: ['light', 'switch', 'click', 'on', 'off', 'power'], tone: ['Suspenseful', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Flight-switch.mp3?alt=media&token=dff9160d-4ac5-4537-b8f1-b98e2ea9ac38' },
  { id: 'sfx_030', name: 'Munchin', tags: ['eating', 'chewing', 'munching', 'food', 'snack', 'crunch'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fmunchin.mp3?alt=media&token=b7a55f80-1e1c-4978-b590-ce6e5d4dbb5b' },
  { id: 'sfx_031', name: 'Oh Noo', tags: ['oh no', 'fail', 'disappointed', 'sad', 'mistake', 'whoops'], tone: ['Comedic', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Foh-noo.mp3?alt=media&token=b5c2bd1d-620f-4fc0-a657-d7d4714f45c7' },
  { id: 'sfx_032', name: 'Basketball', tags: ['basketball', 'dribble', 'bounce', 'sports', 'game', 'court'], tone: ['Dramatic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fbasketball.mp3?alt=media&token=c9459f16-479a-4163-ab63-45fe2c71e1c6' },
  { id: 'sfx_033', name: 'Teeth Chatter', tags: ['teeth', 'chatter', 'cold', 'scared', 'shivering', 'nervous'], tone: ['Suspenseful', 'Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fteeth-chatter.mp3?alt=media&token=9611a6aa-83f8-4a90-a0b4-7a5f1d16864a' },
  { id: 'sfx_034', name: 'Concrete Footsteps', tags: ['footsteps', 'walking', 'concrete', 'steps', 'running', 'chase'], tone: ['Suspenseful', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fconcrete-footsteps.mp3?alt=media&token=317df930-ddad-4c95-a8f7-ee637987dd6c' },
  { id: 'sfx_035', name: 'Growl', tags: ['growl', 'monster', 'beast', 'animal', 'angry', 'snarl'], tone: ['Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fgrowl.mp3?alt=media&token=039481fe-10e4-41ed-8102-2e51eed9547d' },
  { id: 'sfx_036', name: 'Wolf Howl', tags: ['wolf', 'howl', 'moon', 'animal', 'lonely', 'wild'], tone: ['Suspenseful', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fwolf-howl.mp3?alt=media&token=aed8ce2f-03ca-4dc7-8e75-a44456fa81a5' },
  { id: 'sfx_037', name: 'Coin Spin', tags: ['coin', 'spinning', 'money', 'decision', 'chance', 'luck'], tone: ['Suspenseful', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcoin-spinning.mp3?alt=media&token=7a9252b5-3bf1-4bef-a699-fe517419bed0' },
  { id: 'sfx_038', name: 'Siren Alert', tags: ['siren', 'alert', 'emergency', 'warning', 'alarm', 'police', 'ambulance'], tone: ['Suspenseful', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fsiren-alert.mp3?alt=media&token=0feed60d-c191-438b-91d0-a2c11724292e' },
  { id: 'sfx_039', name: 'Whiteboard Marker', tags: ['marker', 'drawing', 'whiteboard', 'circle', 'squeak'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fmarker-circle.mp3?alt=media&token=99d5de79-42d2-428f-9ee0-4af9c5a4677d' },
  { id: 'sfx_040', name: 'Explosion', tags: ['explosion', 'bomb', 'boom', 'blast', 'action', 'loud'], tone: ['Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fexplosion.mp3?alt=media&token=4879eb4d-310b-4edf-967b-90552e166160' },
  { id: 'sfx_041', name: 'Contagious Laughter', tags: ['laughter', 'laughing', 'giggle', 'happy', 'joyful', 'funny'], tone: ['Comedic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcontagious-laughter.mp3?alt=media&token=de516a3c-467f-457a-bf1b-0c81b3aacafd' },
  { id: 'sfx_042', name: 'Jail Door Close', tags: ['jail', 'prison', 'door', 'slam', 'locked', 'cell', 'trapped'], tone: ['Dramatic', 'Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fjaildoorclose.mp3?alt=media&token=dce6bb49-1a0d-4dfe-a500-df86be09dc73' },
  { id: 'sfx_043', name: 'School Bell', tags: ['school', 'bell', 'class', 'alarm', 'ring'], tone: ['Comedic', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fschool-bell.mp3?alt=media&token=72817a89-a288-4572-a55d-ca4a1e92b139' },
  { id: 'sfx_044', name: 'Scream', tags: ['scream', 'yell', 'shout', 'terror', 'horror', 'scared'], tone: ['Dramatic', 'Suspenseful', 'Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fscream.mp3?alt=media&token=e3d89dea-5697-4406-a02b-22889cf6c815' },
  { id: 'sfx_045', name: 'Cellphone Vibration', tags: ['phone', 'vibration', 'buzz', 'cellphone', 'notification', 'call'], tone: ['Suspenseful', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcellphone-vibration.mp3?alt=media&token=6843afdf-e992-4040-ab1b-9028db3795d2' },
  { id: 'sfx_046', name: 'Ticking Stopwatch', tags: ['ticking', 'clock', 'time', 'stopwatch', 'countdown', 'deadline'], tone: ['Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fticking-stopwatch.mp3?alt=media&token=2b73e26b-2f47-42a7-8161-83279e43e694' },
  { id: 'sfx_047', name: 'Suspense Queue', tags: ['suspense', 'tension', 'dramatic', 'ominous', 'sting', 'reveal'], tone: ['Suspenseful', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fsuspense-queue.mp3?alt=media&token=6d3df10a-779e-422c-9dac-a8b4bd0d4f2f' },
  { id: 'sfx_048', name: 'Soft Plop', tags: ['plop', 'drop', 'soft', 'wet', 'funny', 'cartoon'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fsoft-plop.mp3?alt=media&token=b7043017-06ae-4b5e-b8ca-a42bcb1df135' },
  { id: 'sfx_049', name: 'Mmm Hmm', tags: ['mmm-hmm', 'yes', 'agree', 'confirm', 'uh-huh'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fmmm-hmm.mp3?alt=media&token=bc6c580c-f1f6-4000-9733-203f7850e1e5' },
  { id: 'sfx_050', name: 'Court Gavel', tags: ['gavel', 'judge', 'court', 'law', 'justice', 'decision', 'order'], tone: ['Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fgavel-of-justice.mp3?alt=media&token=37d17f39-1dcf-4363-b1b8-a557a1de423d' },
  { id: 'sfx_051', name: 'Ui Sound Off', tags: ['ui', 'click', 'button', 'off', 'toggle', 'interface'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fui-sound-off.mp3?alt=media&token=554db6ba-46fc-453e-bb63-8847383ac132' },
  { id: 'sfx_052', name: 'Doorbell', tags: ['doorbell', 'ding-dong', 'door', 'visitor', 'arrival'], tone: ['Dramatic', 'Suspenseful', 'Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fdoorbell.mp3?alt=media&token=2b4c20a2-175d-4669-aa16-298aadba3305' },
  { id: 'sfx_053', name: 'Snake Hissing', tags: ['snake', 'hiss', 'serpent', 'danger', 'reptile'], tone: ['Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fsnake-hissing.mp3?alt=media&token=a748d83c-4136-4593-a3d1-8bf50824cba3' },
  { id: 'sfx_054', name: 'Plushy Toy', tags: ['plushy', 'squeak', 'toy', 'cute', 'soft', 'squeeze'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fplushy-toy.mp3?alt=media&token=39c2f56d-4674-429c-9c32-caa61c3ad5d1' },
  { id: 'sfx_055', name: 'Cashier Ka Ching', tags: ['cash register', 'ka-ching', 'money', 'sale', 'purchase', 'success'], tone: ['Comedic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcashier-quotka-chingquot.mp3?alt=media&token=fcef0d01-3698-4fd2-95a9-88053549bffc' },
  { id: 'sfx_056', name: 'Money Counter', tags: ['money', 'counting', 'cash', 'bills', 'bank', 'wealth'], tone: ['Dramatic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fmoney-counter.mp3?alt=media&token=23dc2e1f-af2b-46ad-8762-5df928a58c05' },
  { id: 'sfx_057', name: 'Stomach Growling', tags: ['stomach', 'growl', 'hungry', 'rumble', 'food'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fstomach-growling.mp3?alt=media&token=8cd69c11-4245-4ed9-bad4-56fda3a0c9e7' },
  { id: 'sfx_058', name: 'Crowd Laughing', tags: ['crowd', 'laughing', 'audience', 'comedy', 'show', 'happy'], tone: ['Comedic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcrowd-laughing.mp3?alt=media&token=bc3166d0-ce80-47f6-826f-c71195f1590a' },
  { id: 'sfx_059', name: 'Rooster Crowing', tags: ['rooster', 'crowing', 'morning', 'farm', 'wake up', 'dawn'], tone: ['Comedic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fhq-rooster-crowing.mp3?alt=media&token=a87d39ae-19d3-4ae5-9b0e-f711e61e1fa0' },
  { id: 'sfx_060', name: 'Cow Mooing', tags: ['cow', 'moo', 'farm', 'animal', 'cattle'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcow-mooing.mp3?alt=media&token=18f3f8fb-9d63-42e5-933d-337fae9fd6f9' },
  { id: 'sfx_061', name: 'Car Horn', tags: ['car', 'horn', 'honk', 'traffic', 'beep'], tone: ['Comedic', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcar-horn.mp3?alt=media&token=b4e8c922-4b0b-4dae-8074-61b704a2d6df' },
  { id: 'sfx_062', name: 'Creepy Whispering', tags: ['creepy', 'whisper', 'scary', 'ghost', 'horror', 'secret'], tone: ['Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcreepy-whispering.mp3?alt=media&token=22b1f901-145b-44f2-9368-ba377181ecd8' },
  { id: 'sfx_063', name: 'Hammering Nails', tags: ['hammer', 'nail', 'construction', 'building', 'work', 'tools'], tone: ['Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fhitting-nails-with-hammer.mp3?alt=media&token=46601a2f-07e8-441f-81e2-8358981ec2ed' },
  { id: 'sfx_064', name: 'Crowd Shock', tags: ['crowd', 'shock', 'gasp', 'audience', 'surprise', 'reveal'], tone: ['Dramatic', 'Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcrowd-shock.mp3?alt=media&token=9aaceb6e-1b60-4c5e-a168-6bddaddc450c' },
  { id: 'sfx_065', name: 'Aww Cute', tags: ['aww', 'cute', 'reaction', 'sweet', 'adorable'], tone: ['Comedic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Faww-cute-reaction.mp3?alt=media&token=8dfd5cdd-20de-422e-b752-20d84d430f45' },
  { id: 'sfx_066', name: 'Wrong Answer', tags: ['buzzer', 'wrong', 'fail', 'error', 'incorrect', 'game show'], tone: ['Comedic', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fbuzzer-or-wrong-answer.mp3?alt=media&token=f3b012bc-dcad-436b-93b0-bac69b108d58' },
  { id: 'sfx_067', name: 'Whistle', tags: ['whistle', 'call', 'attention', 'wolf whistle', 'catcall'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fcalling-whistle.mp3?alt=media&token=a34243eb-4d45-4b3e-a542-150d57a6f603' },
  { id: 'sfx_068', name: 'Game Over', tags: ['game over', 'lose', 'fail', 'sad', 'end', 'video game'], tone: ['Comedic', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fsweet-game-over.mp3?alt=media&token=f56b6d2a-a7d1-4c00-8a49-79af3391173d' },
  { id: 'sfx_069', name: 'Evil Demonic Laugh', tags: ['evil', 'demonic', 'laugh', 'villain', 'monster', 'scary'], tone: ['Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fevil-demonic-laugh.mp3?alt=media&token=12e4fab6-d4ae-4af1-84db-e5a85669b849' },
  { id: 'sfx_070', name: 'Male Sigh', tags: ['sigh', 'disappointed', 'sad', 'tired', 'relieved', 'exhale'], tone: ['Dramatic', 'Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fmale-sigh.mp3?alt=media&token=8946d234-5508-4dd5-8c1c-81f0f68778ad' },
  { id: 'sfx_071', name: 'Ding', tags: ['ding', 'cartoon', 'idea', 'success', 'correct', 'bell', 'chime'], tone: ['Comedic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fding-cartoon.mp3?alt=media&token=a1aab883-5f78-470c-988e-4d92c67bb476' },
  { id: 'sfx_072', name: 'Lion Roaring', tags: ['lion', 'roar', 'king', 'jungle', 'animal', 'wild'], tone: ['Dramatic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Flion-roaring.mp3?alt=media&token=fdd797b5-d74a-4519-9ed9-bdb1e3d6508e' },
  { id: 'sfx_073', name: 'Elephant Trumpet', tags: ['elephant', 'trumpet', 'animal', 'safari', 'wild'], tone: ['Dramatic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Felephant-trumpet.mp3?alt=media&token=3b516dbd-df48-49b9-9d51-c64bd20f5b38' },
  { id: 'sfx_074', name: 'Robotic Transform', tags: ['robot', 'transform', 'sci-fi', 'machine', 'mech', 'sound design'], tone: ['Dramatic', 'Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Frobotic-transform.mp3?alt=media&token=aa2bb574-72b2-454a-bd52-f1073fc151d7' },
  { id: 'sfx_075', name: 'Error', tags: ['error', 'fail', 'wrong', 'denied', 'computer', 'negative'], tone: ['Comedic', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Ferror.mp3?alt=media&token=23751b7d-e4cb-44f6-968f-825539b46cc5' },
  { id: 'sfx_076', name: 'Bell Ring', tags: ['servant', 'bell', 'ring', 'butler', 'service', 'call'], tone: ['Dramatic', 'Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fservant-bell-ring.mp3?alt=media&token=d8454d3e-8f1c-4410-a479-e080df55dbb0' },
  { id: 'sfx_077', name: 'System Notification', tags: ['notification', 'alert', 'message', 'ui', 'ping', 'system'], tone: ['Dramatic', 'Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fsystem-notification.mp3?alt=media&token=1c2dc3e3-9b96-42b9-b221-60867ad45e70' },
  { id: 'sfx_078', name: 'Broken Bottle', tags: ['bottle', 'break', 'smash', 'glass', 'shatter', 'fight'], tone: ['Dramatic', 'Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fbroken-bottle.mp3?alt=media&token=a36abb84-79a6-49b5-9d92-583437c1f384' },
  { id: 'sfx_079', name: 'Shocked Gasp', tags: ['gasp', 'shocked', 'surprised', 'intake', 'breath', 'scared'], tone: ['Dramatic', 'Suspenseful', 'Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fshocked-gasp.mp3?alt=media&token=1e99af47-138a-43e4-9e72-f99135ebad5e' },
  { id: 'sfx_080', name: 'Wake Up The Robot', tags: ['robot', 'wake up', 'activate', 'power on', 'sci-fi', 'start'], tone: ['Dramatic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fwake-up-the-robot.mp3?alt=media&token=dd52085f-e666-4e91-8ecf-8b15297bceb4' },
  { id: 'sfx_081', name: 'Blocked', tags: ['blocked', 'denied', 'no', 'cannot', 'thud', 'ui'], tone: ['Comedic', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fblocked.mp3?alt=media&token=cfe18e12-8eb3-46f8-b2af-d89ebc293475' },
  { id: 'sfx_082', name: 'Tada Fanfare', tags: ['tada', 'fanfare', 'reveal', 'success', 'magic', 'celebration'], tone: ['Comedic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Ftada-fanfare.mp3?alt=media&token=3df56b29-6b24-4318-ac8b-e776160a6f69' },
  { id: 'sfx_083', name: 'Paper Rip', tags: ['paper', 'rip', 'tear', 'fast', 'shred'], tone: ['Dramatic', 'Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fpaper-rip-fast.mp3?alt=media&token=c4b89174-6943-42c5-8c05-94eede9fbf8e' },
  { id: 'sfx_084', name: 'New Notification', tags: ['notification', 'new', 'alert', 'message', 'ping', 'ui'], tone: ['Dramatic', 'Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fnew-notification.mp3?alt=media&token=bd1d67f2-343b-4d89-b29b-cdcdf829efa9' },
  { id: 'sfx_085', name: 'Yipee', tags: ['yippee', 'yay', 'hooray', 'excited', 'happy', 'celebrate'], tone: ['Comedic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fyipee.mp3?alt=media&token=2ac9c9de-3b49-439c-a636-e8535f0bb2ea' },
  { id: 'sfx_086', name: '90s Game Ui', tags: ['game', 'ui', 'retro', '90s', 'video game', 'bleep'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2F90s-game-ui.mp3?alt=media&token=d22c33b3-a9f1-4eb8-8bd3-8d72c5e24ee1' },
  { id: 'sfx_087', name: 'Bulb Horn Honk', tags: ['horn', 'honk', 'clown', 'cartoon', 'funny', 'bicycle'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fbulb-horn-honk.mp3?alt=media&token=58e4228d-1eba-4fa7-affc-899ae290b17f' },
  { id: 'sfx_088', name: 'Hello', tags: ['hello', 'greeting', 'hi', 'welcome'], tone: ['Comedic', 'Inspirational'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fhello.mp3?alt=media&token=45079aab-2801-44cf-8cda-03fcc2a00ee8' },
  { id: 'sfx_089', name: 'Gasp', tags: ['gasp', 'shock', 'surprise', 'scared', 'dramatic'], tone: ['Dramatic', 'Suspenseful', 'Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fgasp.mp3?alt=media&token=24310b5a-cbcb-49bf-a8d8-9c3c212200eb' },
  { id: 'sfx_090', name: 'Traffic Jam', tags: ['traffic', 'jam', 'cars', 'horns', 'city', 'road'], tone: ['Dramatic', 'Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Ftraffic-jam.mp3?alt=media&token=d2e2ef95-0a91-452b-839a-7f53f358cb75' },
  { id: 'sfx_091', name: 'Umph', tags: ['umph', 'effort', 'grunt', 'lift', 'strain'], tone: ['Comedic', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fumph.mp3?alt=media&token=8ee51663-3044-4ce5-b687-726fb3a48b61' },
  { id: 'sfx_092', name: 'Game Over Arcade', tags: ['game over', 'arcade', 'lose', 'fail', 'retro', '8-bit'], tone: ['Comedic', 'Dramatic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fgame-over-arcade.mp3?alt=media&token=08bb443f-07ef-4b7d-99aa-e93c4d23ed3b' },
  { id: 'sfx_093', name: 'Mouse Click', tags: ['mouse', 'click', 'computer', 'ui', 'button', 'select'], tone: ['Dramatic', 'Suspenseful'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fmouse-click.mp3?alt=media&token=1b6ac626-4d53-490d-824b-8cc31b84175e' },
  { id: 'sfx_094', name: 'Iphone Camera Capture', tags: ['camera', 'shutter', 'photo', 'picture', 'capture', 'phone'], tone: ['Dramatic', 'Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fiphone-camera-capture.mp3?alt=media&token=43669180-b263-4417-af30-41f346faee43' },
  { id: 'sfx_095', name: 'Yuck', tags: ['yuck', 'disgusted', 'gross', 'eww'], tone: ['Comedic'], previewUrl: 'https://firebasestorage.googleapis.com/v0/b/timbro-instant-audio-drama.firebasestorage.app/o/sound-effects%2Fyuck.mp3?alt=media&token=e0954d16-3555-4d8e-91c4-33f108633cc0' },
];

async function deleteCollection(collectionRef: FirebaseFirestore.CollectionReference, batchSize: number) {
  const query = collectionRef.orderBy('__name__').limit(batchSize);

  return new Promise((resolve, reject) => {
    deleteQueryBatch(query, resolve).catch(reject);
  });
}

async function deleteQueryBatch(query: FirebaseFirestore.Query, resolve: (value: unknown) => void) {
  const snapshot = await query.get();

  const batchSize = snapshot.size;
  if (batchSize === 0) {
    // When there are no documents left, we are done
    resolve(true);
    return;
  }

  // Delete documents in a batch
  const batch = db.batch();
  snapshot.docs.forEach((doc) => {
    batch.delete(doc.ref);
  });
  await batch.commit();

  // Recurse on the next process tick, to avoid
  // exploding the stack.
  process.nextTick(() => {
    deleteQueryBatch(query, resolve);
  });
}


async function seedSoundEffects() {
  console.log('Starting to reset and re-seed sound_effects collection...');
  const sfxCollection = db.collection('sound_effects');

  try {
    // Delete all existing documents in the collection
    console.log('Deleting existing sound effects...');
    await deleteCollection(sfxCollection, 50);
    console.log('Existing sound effects deleted successfully.');

    // Seed with new data
    console.log(`Seeding ${mockSoundEffectsLibrary.length} new sound effects...`);
    const batch = db.batch();

    mockSoundEffectsLibrary.forEach((sfx: SoundEffect) => {
      // Use the mock ID as the document ID for consistency
      const docRef = sfxCollection.doc(sfx.id); 
      batch.set(docRef, sfx);
    });

    await batch.commit();
    console.log('Successfully seeded sound_effects collection.');
  } catch (error) {
    console.error('Error resetting Firestore sound_effects:', error);
    process.exit(1);
  }
}

seedSoundEffects();
